### ISSUE TITLE
CPUのパーサを動かす

### ISSUE THREAD

**Issue by kigh-ota** [sacchie/gbem#7]
- [x] ROMファイルをロードする
- [x] ループを始める
- [x] PCを変えながらOpをパースする
- [x] いろいろ

## 完了条件

- テストROMが部分的にでも良いので動く
  - PPUは不要
  - APUも不要
  - 全ROMが動かなくても良い（別Issueで追加対応でもOK）

**Comment by kigh-ota** [comment]
とりあえず
https://github.com/retrio/gb-test-roms/blob/master/cpu_instrs/individual/01-special.gb
を動かす所から。

**Comment by kigh-ota** [comment]
7/18メモ

- 次回、前田さんが続きをやる
- PPUはまたそのうち

**Comment by kigh-ota** [comment]
@## test romのソースの読み方

- 起点は common/build_rom.s の `.org $100` https://github.com/retrio/gb-test-roms/blob/c240dd7d700e5c0b00a7bbba52b53e4ee67b5f15/cpu_instrs/source/common/build_rom.s
- そこから reset に飛ぶ。runtime.s の reset: https://github.com/retrio/gb-test-roms/blob/c240dd7d700e5c0b00a7bbba52b53e4ee67b5f15/cpu_instrs/source/common/runtime.s#L51
- もろもろやった後に $C000 に飛ぶ。これはおそらく、build_rom.s に定義されている slot 1 のこと。https://github.com/retrio/gb-test-roms/blob/c240dd7d700e5c0b00a7bbba52b53e4ee67b5f15/cpu_instrs/source/common/build_rom.s#L6
- 多分 runtime.s の .bank 1 slot 1 https://github.com/retrio/gb-test-roms/blob/c240dd7d700e5c0b00a7bbba52b53e4ee67b5f15/cpu_instrs/source/common/runtime.s#L57
- さらに std_reset (0xc220) に飛ぶ（同ファイル内）

`wreg`というニーモニックが書かれているが、これはマクロでmarco.sに定義されている

**Comment by hmaeta** [comment]
```
set8: d803 <- 199
c09b: OpJrD8(d=4)
c0a1: OpLdR8D8(r=A, d=195)
c0a3: OpLdD16A(d=55297)
set8: d801 <- 195
Exception in thread "main" java.lang.RuntimeException: Invalid opcode: c9, addr: c0a6
	at cpu.ParseKt.parse(parse.kt:333)
	at MainKt.loop(main.kt:11)
	at MainKt.main(main.kt:32)
```
retをパースできなくて処理が落ちているところから。

**Comment by kigh-ota** [comment]
8/8

LYのreadをとりあえず対応したことで
https://github.com/retrio/gb-test-roms/blob/c240dd7d700e5c0b00a7bbba52b53e4ee67b5f15/cpu_instrs/source/common/console.s#L28-L35
のループが動いているはず。
その後、console.s の `@fill_nametable` で 0x9800 に書き込もうとして死亡
```
c3a1: OpLdR16D16(r=HL, d=38912)
c3a4: OpLdR8D8(r=B, d=4)
c3a6: OpLdHLR8(r=A)
Exception in thread "main" java.lang.RuntimeException: Invalid address: 9800
	at MemoryImpl.set8(main.kt:73)
	at cpu.RunKt.run(run.kt:232)
	at MainKt.loop(main.kt:14)
	at MainKt.main(main.kt:32)
```

**Comment by hmaeta** [comment]
toStringのhex対応。

**Comment by kigh-ota** [comment]
8/29

done

- toStringのHex対応はリフレクションで一旦満足することにする
- VRAMの実装をMemoryImplに追加

todo

- テストのアセンブラコードを改めて（いま止まってる所まで）追う
  - 前は、0x9800にデータを書きこむ所まで追ったが、それ以降は追えてない
  - 多分tilemapの後、tile dataの初期をしている
- なにかのI/O Registerを読もうとして死んでるのでそれをなおす？
  - `Exception in thread "main" java.lang.RuntimeException: Invalid address: 0xff83`
  - 多分、HRAM(High RAM)を使ってスプライトデータをDMAで書き込もうとしている？（要確認）
    - https://gbdev.io/pandocs/OAM_DMA_Transfer.html

**Comment by kigh-ota** [comment]
0xc24c は、https://github.com/retrio/gb-test-roms/blob/c240dd7d700e5c0b00a7bbba52b53e4ee67b5f15/cpu_instrs/source/common/runtime.s#L99 の `call reset_crc`

**Comment by kigh-ota** [comment]
https://github.com/retrio/gb-test-roms/blob/c240dd7d700e5c0b00a7bbba52b53e4ee67b5f15/cpu_instrs/source/common/runtime.s

```
(in std_reset:)
C246  call init_printing
C249  call init_testing
C24C  call init_runtime

(in init_runtime:)
C79B  call console_init

(in console_init:)
C36D  call console_hide
```

**Comment by hmaeta** [comment]
```std_reset
-> init_runtime
   -> console_init
　    -> console_hide
         ret
      -> fill_nametable
         0xc3a1: ld hl, 0x9800
         ...
         ret
       0xc37d: ld   hl,TILES+$200
       ...
       0xc385: ld   hl,TILES+$A00


       0xc38d: ld   a,console_width
   -> console_show (0xc39f)
   -> console_apply_scroll_
      0xc482 pop  af
      ret
   ## (macro print_str)
   0xc79e: push hl

   ret
-> reset_crc
```

print_strの中で例外が投げられてそう

**Comment by kigh-ota** [comment]
2023-09-19 作業ログ

```

0xc79e print_str: push hl
0xc0c2 print_str_: pop hl
0xc0c7 print_str_hl: push af
0xc0a7 print_char: push af
0xc05a update_crc: push af
死んでいる：0xc061  ld b,(hl) [hl=checksum+3=0xFF83] ★まずここを実装（HRAMの実装）

→直すと無限ループした

0xd801 print_char_nocrc: ???

CRC = CRC32 チェックサムの計算をしてる？

ログ88704行目で、call print_str_hlからretしてきてすぐjp hlする
hlは0xc7af これはどこ？

0xc04f reset_crc: ???

delay_msec [delay.s]

ログL88719から多分delay_msecのサブルーチンCallに入っている
いろいろあって、call mainに到達
0xc2a6 main: (macro set_test) push hl
★この中で無限ループに入っちゃってる (0xc7d2)
→(01-special.s) set_test 5,"POP AF" の中で 0xc325 jp nz,test_failed が発動しちゃってる

POP AF testとは何か？
bc <- $1200
sp <= bc=$1200
sp=$1200 => af
sp <= af=$1200
sp=$1200 => de
a <- c=$00
a &= $F0  <-0
Compare e=$00 & a=$00  z on
b++ = $13
c++ = $01
(bc=$1301)

sp <= bc=$1301
sp=$1301 => af
sp <= af=$1301
sp=$1301 => de
a <- c=$01
a=$01 &= $F0  -> 0
Compare e=$01 & a=$00

https://www.reddit.com/r/EmuDev/comments/hi237c/gameboy_blargg_test_special01_errors_on_pop_af/
を参考に、POP AFの実装を修正したら直った

別の所から0xC7D2の無限ループに入ってしまった

次回→どこで死亡しているのか特定する
　少し見た。check_crc $6A9F8D8A の中でCRCチェック失敗してfail branchに分岐して forever: に入ったっぽい

**Comment by kigh-ota** [comment]
01-specialが通って、画面表示ができている所を目指すのが良さそう

**Comment by hmaeta** [comment]
```
***** 0xc129: OpCallN16(n=0xC05A)
set16: [0xdfef] <- 0xc12c
****** 0xc05a: OpPushR16(r=AF)                                 // update_crc                                                                                                                                                    
set16: [0xdfed] <- 0xbc60                                                                                                                                                                                          
****** 0xc05b: OpPushR16(r=BC)                                                                                                                                                                                     
set16: [0xdfeb] <- 0x9560                                                                                                                                                                                          
****** 0xc05c: OpPushR16(r=DE)                                                                                                                                                                                     
set16: [0xdfe9] <- 0x7275                                                                                                                                                                                          
****** 0xc05d: OpPushR16(r=HL)                                                                                                                                                                                     
set16: [0xdfe7] <- 0x9930                                                                                                                                                                                          
****** 0xc05e: OpLdR16D16(r=HL, d=0xFF83) 
```

**Comment by kigh-ota** [comment]
マクロ`set_test`は、`push hl`した直後に `call set_test_ (0xC16B)` する。
これをヒントに、どこから `set_test`を使っているか推定できる。
`main` に入った直後から順に
- `set_test 2,"JR negative"` = `0xc2a6`。
- `set_test 3,"JR positive"` = `0xc2cc`
- `set_test 4,"LD PC,HL"` = `0xc2ec`
- `set_test 5,"POP AF"` = `0xc30b`
- `set_test 6,"DAA"` = `0xc32c`

**Comment by hmaeta** [comment]
```
** 0xc350: OpLdR16D16(r=BC, d=0x9560) // check_crc
** 0xc353: OpLdR16D16(r=DE, d=0x7275)
** 0xc356: OpCallN16(n=0xC1F9)
set16: [0xdffb] <- 0xc359
*** 0xc1f9: OpLdFromIoPort(d=0x80)
```

**Comment by hmaeta** [comment]
```
set16: [0xdffb] <- 0xc359
*** 0xc1f9: OpLdFromIoPort(d=0x80) // check_crc_のlda  checksum+0
*** 0xc1fb: OpCpAR8(r=E)
*** 0xc1fc: OpJrFD8(f=NZ, d=0x12)
*** 0xc210: OpCallN16(n=0xC1D8)
set16: [0xdff9] <- 0xc213
**** 0xc1d8: OpPushR16(r=AF)
set16: [0xdff7] <- 0xd540
**** 0xc1d9: OpLdFromIoPor
```

**Comment by hmaeta** [comment]
![スクリーンショット 2023-10-10 202643](https://github.com/sacchie/gbem/assets/12731394/ae3fea31-2871-4430-af2f-6e87a6bb7d94)

**Comment by hmaeta** [comment]
```
** 0xc359: OpJpN16(n=0xC18B) // jp   tests_passed

```

**Comment by kigh-ota** [comment]
`0xc18b`が`tests_passed:`

**Comment by hmaeta** [comment]
```
*** 0xc0c2: OpPopR16(r=HL)  // print_str_のpop  hl
```
